######################################
## Site settings                    ##
######################################
title: Ryan Ward
email: wardyryan1@gmail.com
author: Ryan Ward
description: "A place for my thoughts and ideas."
baseurl: https://ryanward-io.github.io/
date_format: "%-d %b %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

######################################
## Optional features                ##
######################################
animated: false
show_related_posts: false
show_post_footers: True
show_social_icons: True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

###################################
## Social icons                  ##
###################################
github_username: ryanward-io
bitbucket_username:
stackoverflow_id:
twitter_username:
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: ryanward4
angellist_username:
medium_id:
youtube_channel_id:
bitcoin_url:
paypal_url:
flattr_button:

###################################
## Post sharing icons            ##
###################################
show_sharing_icons: True
# Change to 'true' to enable individual icons
share_facebook: True
share_twitter: True
share_googleplus: False
share_linkedin: False
share_digg: False
share_tumblr: False
share_reddit: True
share_stumbleupon: False
share_hackernews: True

text:
  share_buttons:
    text: "Share this post!"
    facebook: "Share on Facebook"
    twitter: "Share on Twitter"
    googleplus: "Share on Google+"
    linkedin: "Share on LinkedIn"
    digg: "Share on Digg"
    tumblr: "Share on Tumblr"
    reddit: "Share on Reddit"
    stumbleupon: "Share on StumbleUpon"
    hackernews: "Share on Hacker News"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "Related Posts"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

############################################
## Build settings                         ##
############################################
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
sass:
  compressed: true
plugins:
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
